{% set name = "rpextractsink" %}
{% set version = "6.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rpExtractSink/archive/refs/tags/{{ version }}.tar.gz
  sha256: abdeb50641d68bdeff1eed648354bdc40123bb6d55c8246b579bcfe2d3742110

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - rr_cache
    - brs_utils
    - rplibs

test:
  requires:
    - python {{ python_min }}
  imports:
    - rpextractsink
  commands:
    - pip check

about:
  home: https://github.com/brsynth/rpExtractSink/tree/main
  summary: "RetroPath2 sink generator"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
    - breakthewall
    - tduigou
